name: pr-description-check
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled


jobs:
  call-pr-description-check-workflow:
    uses: ./.github/workflows/callable.pr-description-check.yaml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
